### PR TITLE
Added two basic examples

### PR DESCRIPTION
**Pull request by KronosTheLate**
As described in [this issue](https://github.com/JuliaDiff/TaylorSeries.jl/issues/276), I think the documentation is too advanced for basic users simply wanting some basic usage.  So I have added two basic examples, which would alleviate the issue a lot.

I would certainly have appreciated them greatly when I found this (very well implemented, good job!) package.

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks a lot for addressing #276 here! The added examples are really clear and nice. And also thanks for your help in improving our package!

If you consider it worth, I would add an example of evaluating the Taylor expansion at a given point, which was the question in the [discourse thread](https://discourse.julialang.org/t/find-taylor-series-of-a-function/51847/7) you quoted. Something like:
```julia
julia> x = Taylor1(3)
 1.0 t + 𝒪(t⁴)

julia> p = exp(1+x)
 2.718281828459045 + 2.718281828459045 t + 1.3591409142295225 t² + 0.45304697140984085 t³ + 𝒪(t⁴)

julia> p(0.01)
2.74560101388203

julia> exp(1.01)
2.7456010150169163
```

**Comment by lbenet** [comment]
One final suggestion, inspired by [your comment](https://github.com/JuliaDiff/TaylorSeries.jl/issues/276#issuecomment-850826456): maybe adding the sentence you suggest in the Readme.md, and linking directly to the section examples there, is worth.

**Comment by KronosTheLate** [comment]
> ```julia
> julia> x = Taylor1(3)
>  1.0 t + 𝒪(t⁴)
> 
> julia> p = exp(1+x)
>  2.718281828459045 + 2.718281828459045 t + 1.3591409142295225 t² + 0.45304697140984085 t³ + 𝒪(t⁴)
> 
> julia> p(0.01)
> 2.74560101388203
> 
> julia> exp(1.01)
> 2.7456010150169163
> ```

I like this example a lot. It should definitely be added!


>One final suggestion, inspired by your comment: maybe adding the sentence you suggest in the Readme.md, and linking directly to the section examples there, is worth.

If you agree with the idea, let's do it. You are more than welcome to edit my PR directly - I will not make your suggested changes right now, as I am busy. If you don't add your suggestions yourself, I'll do it at a later point ^_^

**Comment by lbenet** [comment]
At the moment I'm busy too... we can wait and you complete the example !

**Comment by KronosTheLate** [comment]
> At the moment I'm busy too... we can wait and you complete the example !

Alrighty, I manged to squeeze it in tonight! I felt rude placing the reference to the examples before the nice intro in the `User guide` section, but because I felt that the intro was even a little techincal, I wanted to make sure that the disinterested reader would not fall off before finding the link to the examples. Hope you agree with it, and feel free to make changes!

**Comment by lbenet** [comment]
LGTM. Let us wait that tests pass, and check how the docs are displayed. Then i merge. Thanks a lot!

**Comment by KronosTheLate** [comment]
I see that the PR is merged, but the output is off - it says julia is not defined:
image

I must have messed something up. I don't know how autogenerated docs work, as I have never edited them before. Any idea on what went wrong?

**Comment by lbenet** [comment]
Sorry... I couldn't check the docs because the PR comes from a fork... i think that if you erase the "julia> " in every line of the code, that would avoid the problems; see the `example.md` file further below.

**Comment by lbenet** [comment]
I'm addressing the problem in #278

**Pull request merged**
