### PR TITLE
Separate methods for ^ to use power_by_squaring or pow!

### PR DESCRIPTION
**Pull request by lbenet**

### CODE REVIEW

**Comment by lbenet** [comment]
This implements a suggestion of @dpsanders (off-line discussion)

**Comment by lbenet** [comment]
This makes that `(interval(-1,1) + Taylor1(5)^4` yields the expected result.

**Comment by dpsanders** [comment]
Maybe add some tests with intervals? That would require adding `IntervalArithmetic.jl` to `test/REQUIRE`.

**Comment by lbenet** [comment]
Good point; I'll implement some tests for intervals.

**Comment by lbenet** [comment]
Due to the use of `power_by_squaring`, some intervals arising from `(t-a)^n` (`a` is an `Interval`) are actually wider than the explicit formula, which evaluates `a^k` with appropriate `k`. This is simply the dependency problem.

**Comment by lbenet** [comment]
I think this is ready for review.

**Comment by lbenet** [comment]
Tests are passing and https://github.com/JuliaDiff/TaylorSeries.jl/pull/165/commits/4d5ac348a807345e81c2c83d37ef8264657a57ec provided *narrower* intervals.

**Pull request merged**
