### PR TITLE
Updated notebooks so they make sense for version 3.0.

### PR DESCRIPTION
**Pull request by blas-ko**
Following the discussion on #57, changes made were: 
+  `taylor1_variable` to `Taylor1(::Type,order::Int64)`
+  `diffTaylor` to `derivative`
+ `integTaylor` to `integrate` 
+ correction of *Euler's Four-square identity*
+ minor version details

By the way, There was a method of  `deriv(a,n)` which took the `n`'th derivative of `a` and evaluated it at `t=0`; `derivative` doesn't have that method, maybe it can be implemented.

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks for the contribution! 

Regarding the changes listed above, I agree with all of them except for the last comment on `deriv(a,n)`: it currently corresponds to `derivative(n,a)`. This was proposed by @dpsanders in [this comment](https://github.com/JuliaDiff/TaylorSeries.jl/pull/47#issuecomment-219488013), which was implemented eventually in #47. The lack of news on these changes was due to my laziness: @dpsanders actually suggested to deprecate such things in a more soft way.

So I suggest to include the deleted example with the current notation in the notebook and I merge.

**Comment by blas-ko** [comment]
You're right. I confused what it did for something else... 
updating...

**Comment by blas-ko** [comment]
Julia:0.5 build is not passing with the las commit, no idea why.... Here is the log

```
$ export DEBIAN_FRONTEND=noninteractive
Fix WWDRCA Certificate
$ rvm use
Warning! PATH is not properly set up, '/Users/travis/.rvm/gems/ruby-2.0.0-p648/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.0.0-p648'.
Using /Users/travis/.rvm/gems/ruby-2.0.0-p648
git.checkout
0.94s$ git clone --depth=50 https://github.com/JuliaDiff/TaylorSeries.jl.git JuliaDiff/TaylorSeries.jl
Cloning into 'JuliaDiff/TaylorSeries.jl'...
remote: Counting objects: 722, done.
remote: Compressing objects: 100% (290/290), done.
remote: Total 722 (delta 431), reused 665 (delta 384), pack-reused 0
Receiving objects: 100% (722/722), 846.22 KiB | 0 bytes/s, done.
Resolving deltas: 100% (431/431), done.
$ cd JuliaDiff/TaylorSeries.jl
0.39s$ git fetch origin +refs/pull/77/merge:
remote: Counting objects: 10, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 5), reused 6 (delta 2), pack-reused 0
Unpacking objects: 100% (10/10), done.
From https://github.com/JuliaDiff/TaylorSeries.jl
 * branch            refs/pull/77/merge -> FETCH_HEAD
$ git checkout -qf FETCH_HEAD
Julia for Travis-CI is not officially supported, but is community maintained.
Please file any issues using the following link
  https://github.com/travis-ci/travis-ci/issues/new?labels=julia
and mention `@tkelman`, `@ninjin`, `@staticfloat` and `@simonbyrne` in the issue
Installing Julia
0.03s$ CURL_USER_AGENT="Travis-CI $(curl --version | head -n 1)"
333.85s$ curl -A "$CURL_USER_AGENT" -s -L -o julia.dmg 'https://s3.amazonaws.com/julialang/bin/osx/x64/0.5/julia-0.5-latest-osx10.7+.dmg'
The command "curl -A "$CURL_USER_AGENT" -s -L -o julia.dmg 'https://s3.amazonaws.com/julialang/bin/osx/x64/0.5/julia-0.5-latest-osx10.7+.dmg'" failed and exited with 56 during .
Your build has been stopped.
/Users/travis/build.sh: line 138: shell_session_update: command not found
```

**Comment by lbenet** [comment]
LGTM. Merging. Thanks!

**Pull request merged**
