### PR TITLE
Fix integrate for several variables and add simple tests

### LINKED ISSUE #146: integrate doesn't work with >2 variables
```jl
julia> x, y = set_variables("x y")
2-element Array{TaylorSeries.TaylorN{Float64},1}:
  1.0 x + 𝒪(‖x‖⁷)
  1.0 y + 𝒪(‖x‖⁷)

julia> integrate(x, 1)   # 2 variables seems to work
 0.5 x² + 𝒪(‖x‖⁷)

julia> x, y, z = set_variables("x y z")
3-element Array{TaylorSeries.TaylorN{Float64},1}:
  1.0 x + 𝒪(‖x‖⁷)
  1.0 y + 𝒪(‖x‖⁷)
  1.0 z + 𝒪(‖x‖⁷)

julia> integrate(z, 1)   # 3 variables doesn't
ERROR: AssertionError: order ≤ get_order() && lencoef ≤ num_coeffs
Stacktrace:
 [1] resize_coeffsHP!(::Array{Float64,1}, ::Int64) at /Users/dpsanders/.julia/v0.6/TaylorSeries/src/auxiliary.jl:37
 [2] Type at /Users/dpsanders/.julia/v0.6/TaylorSeries/src/constructors.jl:96 [inlined]
 [3] integrate(::TaylorSeries.HomogeneousPolynomial{Float64}, ::Int64) at /Users/dpsanders/.julia/v0.6/TaylorSeries/src/calculus.jl:316
 [4] integrate(::TaylorSeries.TaylorN{Float64}, ::Int64) at /Users/dpsanders/.julia/v0.6/TaylorSeries/src/calculus.jl:333

```

### PR DESCRIPTION
**Pull request by dpsanders**
Fixes #146.

### CODE REVIEW

**Comment by dpsanders** [comment]
Tests pass on 0.6.
Something is going wrong with allowing failures on 0.7.

Shall we merge anyway?

**Comment by dpsanders** [comment]
Apparently I didn't have latest master with latest `.travis.yml`.
Have now rebased against latest master which should hopefully fix the problem.

**Comment by dpsanders** [comment]
@lbenet This is ready to merge.

**Comment by lbenet** [comment]
Thanks a lot! I'll merge this!

**Comment by lbenet** [comment]
Incidentally, the problem with some tests for Julia 0.7 seems to be related to the need of loading certain parts which in 0.7 are the stdlib. I have done already something on this, without caring about 0.6 compatibility; see the branch `deprecations0.7`.

**Pull request merged**
