### PR TITLE
Correct the returned series when factorizing, with tests

### LINKED ISSUE #58: sqrt gives misleading O() term
```
julia> t = Taylor1(10)
 1.0 t + 𝒪(t¹¹)

julia> sqrt(t^2 + t^3)
 1.0 t + 0.5 t² - 0.125 t³ + 0.0625 t⁴ - 0.0390625 t⁵ + 0.02734375 t⁶ - 0.0205078125 t⁷ + 0.01611328125 t⁸ + 𝒪(t¹¹)
```

This seems to imply that the t^9 and t^10 terms have zero coefficients, which is incorrect.

### PR DESCRIPTION
**Pull request by lbenet**
This fixes #58 and other similar cases.

### CODE REVIEW

**Comment by lbenet** [comment]
I'll add a summary here: Currently, in master, we get the following:

```julia
julia> t = Taylor1(5)
 1.0 t + 𝒪(t⁶)

julia> 1/(1+t)
 1.0 - 1.0 t + 1.0 t² - 1.0 t³ + 1.0 t⁴ - 1.0 t⁵ + 𝒪(t⁶)

julia> t/(t+t^2) # should be identical to the result above
 1.0 - 1.0 t + 1.0 t² - 1.0 t³ + 1.0 t⁴ + 𝒪(t⁶)

julia> t*sqrt(1+t)
 1.0 t + 0.5 t² - 0.125 t³ + 0.0625 t⁴ - 0.0390625 t⁵ + 𝒪(t⁶)

julia> sqrt(t^2+t^3) # should be identical to the result above
 1.0 t + 0.5 t² - 0.125 t³ + 𝒪(t⁶)
```

This PR corrects this.

**Comment by lbenet** [comment]
Tests should pass now...

**Comment by lbenet** [comment]
@dpsanders I think this is ready!

**Comment by dpsanders** [comment]
I don't follow the calculations, but if the new tests work, LGTM!

**Comment by lbenet** [comment]
The basic idea is to mimic an "extension" of the order of the independent variable, by using zeros appropriately; this is used to compute the coefficients (which before were simply set to zero) to the correct order.

Considering the example of `sqrt(t^2+t^3)` with `t=Taylor1(5)`, the idea is to treat the independent variable of the expression as being of order 7 (instead of order 5), because `t^2` can be factorized (which are the two orders lost in the returned expression). So the idea is to mimic the behavior of `sqrt( `Taylor1(7)^2+Taylor1(7)^3 )` (using `t` and zeros for order 6 and 7) and return the result up to order 5.

I hope this short explanation makes some sense.

**Pull request merged**
