### PR TITLE
Add `evaluate!` method for higher-dim AbstractArray

### PR DESCRIPTION
**Pull request by PerezHz**
See related discussion in https://github.com/PerezHz/TaylorIntegration.jl/pull/114#discussion_r524805200

### CODE REVIEW

**Review by lbenet — COMMENTED** [review]
This is a general comment on this PR: there are other entries which could be updated as you  are proposing for `evaluate!`, i.e., instead of having `Array{T,1}` or `SubArray{T}` (or their unions) have `AbstractArray{T,N}`. I propose  to change them all to be consistent. Have you consider them?

**Comment by PerezHz** [comment]
Thanks @lbenet I pushed a commit addressing other methods with `Array` and `SubArray`, as well as `Union`s thereof

**Comment by lbenet** [comment]
Thanks a lot! LGTM. 

After merging this PR, I think we should tag a new patch version; do  you agree @dpsanders?

**Comment by lbenet** [comment]
Merged... thanks!

**Comment by PerezHz** [comment]
Thanks for merging! Once the new release is registered, I'll update https://github.com/PerezHz/TaylorIntegration.jl/pull/114 accordingly

**Comment by lbenet** [comment]
The new version is already tagged; you can go ahead and update https://github.com/PerezHz/TaylorIntegration.jl/pull/114; I'll take a look on it later.

**Pull request merged**
