### PR TITLE
Add displayBigO to set/unset printing the bigO notation

### PR DESCRIPTION
**Pull request by lbenet**
This commit also addresses some deprecation warnings for Julia 0.7.

### CODE REVIEW

**Comment by lbenet** [comment]
Addresses #134.

@dpsanders Can you suggest a better name than `displayBigO`? Once this is set, I'll add it to the documentation.

**Comment by lbenet** [comment]
Once #137 is merged, it will require a rebase...

**Comment by lbenet** [comment]
Rebased to current master...

**Comment by lbenet** [comment]
@dpsanders Suggestion for a better name, instead of `displayBigO`? 

I just added the docs, and think this is ready to be reviewed and perhaps merged.

**Comment by lbenet** [comment]
If it's ok with you @dpsanders, I'll merge this PR and tag a new version. 

Due to the changes introduced in #135 I guess the proper thing to do is to tag it as 0.7.0. Some development in TaylorIntegration is awaiting for such new tag...

**Comment by lbenet** [comment]
Merged!

**Comment by dpsanders** [comment]
Sorry I didn't get round to looking at it. It's very nice, thanks!

**Pull request merged**
