### PR TITLE
Use new syntax of Julia 0.6

### PR DESCRIPTION
**Pull request by lbenet**
This is WIP aimed to use the new syntax introduced in Julia 0.6, to eventually drop the support for Julia 0.5.x.

### CODE REVIEW

**Comment by dpsanders** [comment]
Have you seen 
https://juliacomputing.com/blog/2017/08/17/femtocleaner.html
?

**Comment by lbenet** [comment]
I heard, and forgot about it :-P

Thanks for reminding me.

**Comment by blas-ko** [comment]
Is this still WIP?

**Comment by lbenet** [comment]
I have just changed the title of this PR. 

While I think this is essentially done, I think a new version (0.5.1) should be released that is the last one supporting Julia 0.5. This could then be merged, and perhaps we should also tag a new version (0.6.0) which includes this PR. Following this plan, a few changes may still be needed...

@dpsanders What do you think about this?

**Comment by dpsanders** [comment]
I agree with making a final 0.5 release if there's something new.

**Comment by lbenet** [comment]
(Rebased to current master)

**Comment by lbenet** [comment]
I just tagged v0.5.1, commit 909689b3db0521bcac203d19a1669d1cd05d44cb, with a bunch of additions; it is the last version compatible with Julia 0.5.+. The idea is, once that version is in accepted in METADATA, this PR can be merged and it will tagged as v0.6.0. This supports Julia 0.6.0+ and above. Tests are passing.

**Comment by lbenet** [comment]
I have retouched and updated some parts of the docs. I think this is ready to be merged and tagged as 0.6, so we drop support to Julia 0.5.x. Do you agree @dpsanders ?

**Comment by dpsanders** [comment]
Yes, great, go ahead!

**Comment by lbenet** [comment]
Done! I just tagged and submitted the PR to METADAT.

**Pull request merged**
