### PR TITLE
Fix equation rendering in docstrings

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks for this PR! I didn't notice that there are some equations which were not rendered properly. 

Since you are onto this, could you also fix (delete the `{eqnarray*}` environments) for [`TaylorSeries.sqr!`](https://github.com/JuliaDiff/TaylorSeries.jl/blob/28ad329f06e8a50bdc372fc3c57f5939f9d59cfc/src/power.jl#L281) and [`TaylorSeris.sqrt!`](https://github.com/JuliaDiff/TaylorSeries.jl/blob/28ad329f06e8a50bdc372fc3c57f5939f9d59cfc/src/power.jl#L412)?

**Comment by lbenet** [comment]
I deployed the docs locally, and it seems these fixes are not fixing the rendering of those equations. Checking the documentation on `Documenter.jl` [here](https://documenter.juliadocs.org/stable/man/latex/#Display-Equations), it seems we do need the `{aligned}` environments.

**Comment by navidcy** [comment]
Done

**Comment by lbenet** [comment]
I've tried locally and it still doesn't solve the problem. I'm not sure why is that happening; it may be related to the use of `@doc doc"""..."""`, or the fact that it is rendered in html; the docstrings seem ok though.

**Comment by navidcy** [comment]
When I build the docs locally with
```
julia --color=yes --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'; julia --color=yes --project=docs docs/make.jl
```
they seem ok.

Screen Shot 2022-11-25 at 4 24 05 am

**Comment by lbenet** [comment]
I can't check it, but let's go ahead and see if it works. So I'll merge.

Thanks for your contribution!

**Comment by navidcy** [comment]
Seems ok!
https://juliadiff.org/TaylorSeries.jl/latest/api/#TaylorSeries.sqr!

**Comment by lbenet** [comment]
Excellent! Thanks again!

**Pull request merged**
