### PR TITLE
Refactor hash table generation.

### PR DESCRIPTION
**Pull request by dpsanders**
This is a drop-in replacement for the previous version except that the exact order
in which each set of indices is generated is changed. 

~~The performance is basically the same as in the previous version.~~
EDIT: The performance is now significantly better: 8.4s instead of 12s for the first Fateman test on my machine!

Follows on from #22

### CODE REVIEW

**Comment by lbenet** [comment]
Can you also rebase this PR?

While I like a lot the new implementation of the tables, I'm checking if it can be optimized a bit more. In my machine, the Fatemann tests (julia 0.4) lasts 3.84 sec, versus Mathematica 3.17, so we are within 20%.

**Comment by dpsanders** [comment]
In my next work I have gained another factor of 2.5 ;)  I'll put it up as a new PR, but I am having problems rebasing this one...

**Comment by lbenet** [comment]
Tests are currently failing due to some recent change JuliaLang/julia#12285. 

Shall I try to fix this and incorporate the modifications in the tests?

**Comment by dpsanders** [comment]
I have fixed the FactCheck syntax, that has changed from `=>` to `-->`. However, there is a mess with merge conflicts due to rebasing the previous PRs :/

**Comment by lbenet** [comment]
Rebase and squash is done... Tests pass, so I'm merging.

**Pull request merged**
