### PR TITLE
Extend broadcasted to all TaylorSeries types

### LINKED ISSUE #199: Rounding Not Defined on TaylorSeries
Rounding on `Taylor1{T}` could be defined to return a new `Taylor1` whose coefficients are rounded to the appropriate type.
i.e.
```
t = Taylor1(1.,3) #type Taylor1{Float64}
Float32(t) # Method Error
# expect == Taylor1(Float32(1.),3)
```

### PR DESCRIPTION
**Pull request by lbenet**
Fix #199

### CODE REVIEW

**Comment by lbenet** [comment]
@dpsanders I have implemented broadcasting as suggested; note that no change to `eltype` was made.

**Comment by lbenet** [comment]
This is ready for review

**Comment by lbenet** [comment]
Rebase to current master...

**Comment by lbenet** [comment]
@dpsanders @jessebett Can you provide some feedback on this?

**Comment by lbenet** [comment]
@dpsanders Shall I go ahead and merge this?

**Comment by jessebett** [comment]
@lbenet sorry this got lost in my github notifications. I will look at this branch and see if I'm running into anything.

**Comment by dpsanders** [comment]
LGTM!

**Comment by jessebett** [comment]
I thought this was supposed to solve something like

```
[5.] .* Taylor1(1.,6) 
#ERROR: MethodError: no method matching Float64(::Taylor1{Float64})
```

Currently fails on this branch.

**Comment by lbenet** [comment]
Thanks again for reporting; I'll see what's going on...

**Comment by lbenet** [comment]
@jessebett I think the problem is related to some `promotion` or `conversion` rules. While `[5.] .* Taylor1(1.,6)` throws the error you reported, the following works as expected:
```julia
julia> [Taylor1(5)] .* Taylor1(1.,6)
1-element Array{Taylor1{Float64},1}:
  1.0 t + 𝒪(t⁷)
```

**Comment by jessebett** [comment]
It's strange that this promotion problem happens here and not, for instance, with `5. * Taylor1(1.,6)`. 

I'd expect the earlier error to return the same as [5.] .* 1. but Taylor

**Comment by lbenet** [comment]
Rebasing to current master.

**Comment by lbenet** [comment]
Closing in favor of #207

**Pull request closed without merging**
