### PR TITLE
Refactoring of table names, and splitting out files

### PR DESCRIPTION
**Pull request by dpsanders**
Follows on from #21.

After the experience with #16 , I have left all the commits as atomic as possible.
I can rebase and squash later if desired.

### CODE REVIEW

**Comment by lbenet** [comment]
Once we decide on #21, I think this is ready.

I guess that squashing this into 2 or 3 commits makes it nicer. Yet, I don't know what this will cause on #23...

**Comment by lbenet** [comment]
@dpsanders I just merged #21. Could you rebase and squash this commit, to merge it?

**Comment by dpsanders** [comment]
Rebased, squashed and green -- merging!

(I incorporated your two suggestions from #21.)

**Comment by lbenet** [comment]
Great!

**Pull request merged**
