### PR TITLE
use isdefined for iszero instead of VERSION check

### PR DESCRIPTION
**Pull request by tkelman**

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks for the corrections! I'll wait to get green lights in travis before merging. (I restarted one test in travis because it failed due to some odd reason.)

Can you confirm the way to proceed? First I delete the release (v0.5.0), then merge, and then resubmit a new release? 

Do I have to do something in METADATA?

**Comment by lbenet** [comment]
Merging! Thanks again!

**Comment by tkelman** [comment]
looks like you figured it out, but ref https://github.com/attobot/attobot#updatingdeleting-a-release

**Comment by lbenet** [comment]
Thanks! I recall that I had read it somewhere! Thanks anyway!

**Pull request merged**
