### PR TITLE
Integration of TaylorN series

### PR DESCRIPTION
**Pull request by lbenet**
Solves #130.

### CODE REVIEW

**Comment by lbenet** [comment]
Docs are still needed.

**Comment by lbenet** [comment]
Also note that this was built on top of #135

**Comment by dpsanders** [comment]
Could you rebase, please?

**Comment by lbenet** [comment]
Yes, I am actually on this... I'll ping you when this is ready

**Comment by lbenet** [comment]
Done!

**Comment by lbenet** [comment]
@dpsanders Any comments?

**Comment by lbenet** [comment]
Merged!

**Pull request merged**
