### PR TITLE
Solves issue #24 throwing an ErrorException; includes tests

### PR DESCRIPTION
**Pull request by lbenet**

### CODE REVIEW

**Comment by lbenet** [comment]
I don't love the error messages, but are ok for the time being. Feel free to change them (also in Taylor1). I don't know yet how to use `throw` properly...

Tests pass.

**Comment by dpsanders** [comment]
To use `throw` you need to pick what type of exception it is: http://julia.readthedocs.org/en/latest/manual/control-flow/#exception-handling

E.g. for the `sqrt`, it's either a DomainError or an ArgumentError. So something like

```julia
if p0 == 0
    throw(ArgumentError("First Taylor coefficient must be non-zero for sqrt"))
end
```
This is tested with
```julia
@fact_throws ArgumentError sqrt(0)
```

**Comment by lbenet** [comment]
Thanks. I'll do the changes later... no time right now.

**Comment by lbenet** [comment]
Thanks for the comments. Errors are now handled with `throw`, including some tests that were commented.

Tests pass...

**Comment by lbenet** [comment]
I added one new commit, to replace `FloatingPoint` by `AbstractFloat`, and also removed unnecessary @compat statements

Tests are not passing though, because the tagged version of `Compat.jl` doesn't yet include the changes related to `AbstractFloat`... I opened an issue: https://github.com/JuliaLang/Compat.jl/issues/135

This can be merged once a new tagged version of Compat.jl appears.

**Comment by lbenet** [comment]
New version tagged for Compat.jl; tests pass. I'm merging this...

**Comment by dpsanders** [comment]
Looks nice!

**Comment by dpsanders** [comment]
Hmmm, don't you need to add the required minimum version of `Compat` in the `REQUIRE` file?

**Comment by lbenet** [comment]
I'm not quite sure what do you mean. I thought that `Compat.jl` precisely was taking care of this.

**Comment by dpsanders** [comment]
You need to specify which version of `Compat.jl` is required for `TaylorSeries.jl`. Otherwise, if someone tries to use the package with a previous version of `Compat.jl`, the code will break, e.g. with Julia 0.3 and Compat 0.5.1 I get

```
julia> using TaylorSeries
ERROR: AbstractFloat not defined
```
If you change `Compat` to `Compat 0.6` in `REQUIRE`, then when I try to install `TaylorSeries` it should make sure that necessary version of `Compat` is installed.

**Comment by lbenet** [comment]
Thanks for clarifying this.

I just tried to push a commit with the corresponding change, but I can't see it in this branch...

**Pull request merged**
