### PR TITLE
Update documentation and use html format

### PR DESCRIPTION
**Pull request by lbenet**

### CODE REVIEW

**Comment by lbenet** [comment]
I just pushed another commit and, except for an overall review, I think this is ready to be merged. 

@dpsanders Do you have some time to review this? I do not know if it is possible to see the changes in the docs on line, but at least locally you can. You have to go to the `docs/`, excute there the `make.jl` file (currently I am using Julia 0.5, but it should also work in Julia 0.6), and open in whatever browser the files that have been created in the `build/` subfolder.

Then, eventually, we may think about tagging version 0.5...

**Comment by dpsanders** [comment]
I get the following error from the `docs` branch:
```
20:36 $ julia docs/make.jl
WARNING: OhMyREPL not installed
Documenter: setting up build directory.
Documenter: expanding markdown templates.
 !! Undefined binding 'TaylorSeries.max_order'. [src/api.md]
ERROR: LoadError: AssertionError: order ≤ get_order() && lencoef ≤ num_coeffs
 in resize_coeffsHP!(::Array{Float64,1}, ::Int64) at /Users/dpsanders/.julia/v0.5/TaylorSeries/src/auxiliary.jl:36
 in Type at /Users/dpsanders/.julia/v0.5/TaylorSeries/src/constructors.jl:86 [inlined]
 in Type at /Users/dpsanders/.julia/v0.5/TaylorSeries/src/constructors.jl:92 [inlined]
 in macro expansion at /Users/dpsanders/.julia/v0.5/TaylorSeries/src/arithmetic.jl:47 [inlined]
 in macro expansion at ./simdloop.jl:73 [inlined]
 in zeros(::TaylorSeries.HomogeneousPolynomial{Float64}, ::Int64) at /Users/dpsanders/.julia/v0.5/TaylorSeries/src/arithmetic.jl:46
 in TaylorSeries.TaylorN{Float64}(::Array{TaylorSeries.HomogeneousPolynomial{Float64},1}, ::Int64) at /Users/dpsanders/.julia/v0.5/TaylorSeries/src/constructors.jl:145
 in zero(::TaylorSeries.TaylorN{Float64}) at /Users/dpsanders/.julia/v0.5/TaylorSeries/src/arithmetic.jl:35
 in pretty_print(::TaylorSeries.TaylorN{Float64}) at /Users/dpsanders/.julia/v0.5/TaylorSeries/src/printing.jl:94
 in show at /Users/dpsanders/.julia/v0.5/TaylorSeries/src/printing.jl:231 [inlined]
 in show at ./replutil.jl:4 [inlined]
 in display at ./multimedia.jl:111 [inlined]
 in display(::TextDisplay, ::TaylorSeries.TaylorN{Float64}) at ./multimedia.jl:112
 in disable_color(::Documenter.DocChecks.##13#14{TaylorSeries.TaylorN{Float64},TextDisplay}) at /Users/dpsanders/.julia/v0.5/Documenter/src/DocChecks.jl:558
 in result_to_string(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::TaylorSeries.TaylorN{Float64}) at /Users/dpsanders/.julia/v0.5/Documenter/src/DocChecks.jl:281
 in runner(::Type{Documenter.Expanders.REPLBlocks}, ::Base.Markdown.Code, ::Documenter.Documents.Page, ::Documenter.Documents.Document) at /Users/dpsanders/.julia/v0.5/Documenter/src/Expanders.jl:510
 in dispatch(::Type{Documenter.Expanders.ExpanderPipeline}, ::Base.Markdown.Code, ::Documenter.Documents.Page, ::Documenter.Documents.Document) at /Users/dpsanders/.julia/v0.5/Documenter/src/Selectors.jl:164
 in expand(::Documenter.Documents.Document) at /Users/dpsanders/.julia/v0.5/Documenter/src/Expanders.jl:29
 in dispatch(::Type{Documenter.Builder.DocumentPipeline}, ::Documenter.Documents.Document) at /Users/dpsanders/.julia/v0.5/Documenter/src/Selectors.jl:164
 in cd(::Documenter.##2#3{Documenter.Documents.Document}, ::String) at ./file.jl:59
 in #makedocs#1(::Bool, ::Array{Any,1}, ::Function) at /Users/dpsanders/.julia/v0.5/Documenter/src/Documenter.jl:198
 in (::Documenter.#kw##makedocs)(::Array{Any,1}, ::Documenter.#makedocs) at ./<missing>:0
 in include_from_node1(::String) at ./loading.jl:488
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:265
 in _start() at ./client.jl:321
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/dpsanders/.julia/v0.5/TaylorSeries/docs/make.jl, in expression starting on line 3
```

**Comment by dpsanders** [comment]
(Sorry, my branch was out of date, ignore the previous comment that I deleted.)

**Comment by dpsanders** [comment]
```
 > checking for missing docstrings.
 !! 1 docstring potentially missing:

    TaylorSeries
```

**Comment by dpsanders** [comment]
I haven't read it in detail, but in general it looks very nice!

Have you considered using `jldoctest` for simulated terminal sessions? That would probably be a nice addition.

**Comment by lbenet** [comment]
Thanks for taking a look in all this. Yes, I did considered using `jldoctes`, but I decided to let `Documenter.jl` generate the output; it's easier to mantain! 😄 

Regarding the warning above, I guess I should add a short description about what the module does.

**Comment by dpsanders** [comment]
Ah, I didn't realise it automatically generates the output! Yes, that sounds great!

I'm anxious to see the equivalent for ValidatedNumerics.jl! ;)

**Comment by lbenet** [comment]
> I'm anxious to see the equivalent for ValidatedNumerics.jl! ;)

I'll work on that during the week end :P

**Comment by lbenet** [comment]
Something strange is happening with the tests on osx and v0.7-dev...

**Comment by lbenet** [comment]
After restarting travis due to some problems with the tests, they pass. I'm merging this to see the docs online.

**Pull request merged**
