### PR TITLE
Updates in the documentation related to big O notation

### PR DESCRIPTION
**Pull request by lbenet**
Related to changes introduced by #6 
[ci skip]

### CODE REVIEW

**Comment by lbenet** [comment]
Whenever this is merged, I will update the gh-pages branch...

**Comment by dpsanders** [comment]
Actually, I think it would be better to update the `gh-pages` branch now, so that the documentation can be checked in its final form. Looks good though. (Sorry about the work that this must have been!)

**Comment by lbenet** [comment]
Done.

For consistency of the version (in `master`), I think it is better to update the `gh-pages` branch once the docs are merged.

**Comment by lbenet** [comment]
(This time I did include the [ci skip] in the commit message!)

**Comment by lbenet** [comment]
I'm merging this, to update the `gh-pages` branch as well

**Pull request merged**
