### PR TITLE
RFC: Add `rad2deg`, `deg2rad` for Taylor1 and TaylorN

### PR DESCRIPTION
**Pull request by PerezHz**
Self-explaining title 😉... Was working with these functions with Taylor1 and thought it'd be nice to add them to TaylorSeries!

### CODE REVIEW

**Comment by lbenet** [comment]
Thanks! LGTM!

If you are using it together with `TaylorIntegration`, it is maybe a good idea to include the equivalent mutating functions, e.g., `rad2deg(res, a, k)`. This is of interest in the context of https://github.com/PerezHz/TaylorIntegration.jl/pull/31

**Comment by PerezHz** [comment]
> If you are using it together with TaylorIntegration, it is maybe a good idea to include the equivalent mutating functions, e.g., rad2deg(res, a, k). This is of interest in the context of PerezHz/TaylorIntegration.jl#31

That's actually a really nice suggestion! Sure, I'll add them right away!

**Comment by lbenet** [comment]
Be sure to add them in the dictionaries that are used in `TaylorIntegration`. Let me know when you are ready...

**Comment by lbenet** [comment]
I just noticed that you will have to rebase...

**Comment by PerezHz** [comment]
> Be sure to add them in the dictionaries that are used in TaylorIntegration. 

Good catch! Just rebased to current master, added the mutating functions, updated the `Dict`s and also added corresponding tests

**Comment by PerezHz** [comment]
Just saw that #143 is about to be merged... I can re-rebase to latest master once that PR is merged

**Pull request merged**
