### PR TITLE
Solve invalidations

### LINKED ISSUE #339: Invalidation
hey, 

using [this tutorial](https://timholy.github.io/SnoopCompile.jl/dev/tutorial/) on my particular workflow, I endeed up with a lot of invalidations in TaylorSeries.jl as follows: 

````julia
julia> trees[end]
inserting convert(::Type{Array{TaylorSeries.Taylor1{TaylorSeries.TaylorN{T}}, N}}, s::Array{TaylorSeries.TaylorN{TaylorSeries.Taylor1{T}}, N}) where {T<:Union{Real, Complex}, N} @ TaylorSeries C:\Users\lrnv\.julia\packages\TaylorSeries\OLHVb\src\conversion.jl:140 invalidated:
   backedges: 1: superseding convert(::Type{T}, a::AbstractArray) where T<:Array @ Base array.jl:613 with MethodInstance for convert(::Type{Vector{_A}} where _A, ::Vector) (1 children)
              2: superseding convert(::Type{T}, a::AbstractArray) where T<:Array @ Base array.jl:613 with MethodInstance for convert(::Type{<:Vector}, ::Vector) (263 children)

julia> 
````
Looks like the problematic method is the convert method there : https://github.com/JuliaDiff/TaylorSeries.jl/blob/ff1f6806dcd65ac6af9e417bcfd71ce483abfa3e/src/conversion.jl#L140-L148 which invalidates a bunch of convertion already defined in base. 

The second one is a promote rule, also from `TaylorSeries.jl`: 

````julia
julia> trees[end-1]
inserting promote_rule(::Type{S}, ::Type{T}) where {S<:Union{Real, Complex}, T<:AbstractSeries} @ TaylorSeries C:\Users\lrnv\.julia\packages\TaylorSeries\OLHVb\src\conversion.jl:201 invalidated:
   backedges:  1: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{UInt64}, ::Type{<:Integer}) (1 children)
               2: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{UInt8}, ::Type{<:Integer}) (1 children)       
               3: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{UInt16}, ::Type{<:Integer}) (1 children)      
               4: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{Int64}, ::Type{<:Integer}) (2 children)       
               5: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{Int64}, ::Type{S} where S<:Unsigned) (2 children)
               6: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{Int64}, ::Type{S} where S<:Real) (2 children) 
               7: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{UInt64}, ::Type) (3 children)
               8: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{UInt8}, ::Type) (3 children)
               9: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{UInt16}, ::Type) (3 children)
              10: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{UInt8}, ::Type{T} where T<:Unsigned) (4 children)
              11: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{UInt64}, ::Type{T} where T<:Unsigned) (5 children)
              12: superseding promote_rule(::Type, ::Type) @ Base promotion.jl:319 with MethodInstance for promote_rule(::Type{Int64}, ::Type) (6 children)


````

defined there: https://github.com/JuliaDiff/TaylorSeries.jl/blob/ff1f6806dcd65ac6af9e417bcfd71ce483abfa3e/src/conversion.jl#L201-L202

Do you think we could do somehting about it ? I admit that I dont know what to do with this :)

<details>
<summary>Code I ran</summary>

````julia
using SnoopCompileCore
invalidations = @snoopr using Distributions, Copulas
tinf = @snoopi_deep begin
    biv_cops = [
        GaussianCopula([1 0.7; 0.7 1]),
        TCopula(2,[1 0.7; 0.7 1]),
        ClaytonCopula(2,7),
        JoeCopula(2,3),
        GumbelCopula(2,8),
        FrankCopula(2,0.5),
        AMHCopula(2,0.7)]
    for C in biv_cops
        u = rand(C,10)
        pdf(C,[0.5,0.5])
        cdf(C,[0.5,0.5])
        D = SklarDist(C,[Gamma(1,1),Normal(1,1)])
        u = rand(D,10)
        pdf(D,[0.5,0.5])
        cdf(D,[0.5,0.5])
    end

    X₁ = Gamma(2,3)
    X₂ = Pareto()
    X₃ = LogNormal(0,1)
    C = ClaytonCopula(3,0.7) # A 3-variate Clayton Copula with θ = 0.7
    D = SklarDist(C,(X₁,X₂,X₃)) # The final distribution
    simu = rand(D,1000)
    D̂ = fit(SklarDist{FrankCopula,Tuple{Gamma,Normal,LogNormal}}, simu)
end
using SnoopCompile
trees = invalidation_trees(invalidations)
staletrees = precompile_blockers(trees, tinf)

@show length(uinvalidated(invalidations))  # show total invalidations

show(trees[end])  # show the most invalidating method
````

</details>

### PR DESCRIPTION
**Pull request by lbenet**
Fixes #339

### CODE REVIEW

**Comment by lbenet** [comment]
@lrnv Does this help to solve the invalidations? There are still some triggered when IntervalArithmetic is loaded; I'll try to solve them, but IntervalArithmetic is currently under deep revision...

**Comment by lbenet** [comment]
Following the code [in this comment](https://github.com/JuliaDiff/TaylorSeries.jl/issues/339#issue-1974616422), using the code in this branch, I now get:

```julia
julia> show(trees[end])  # show the most invalidating method
inserting broadcasted(::Base.Broadcast.DefaultArrayStyle{N}, op, r::FillArrays.AbstractFill{T, N}) where {T, N} @ FillArrays ~/.julia/packages/FillArrays/2eiCe/src/fillbroadcast.jl:78 invalidated:
   backedges: 1: superseding broadcasted(::S, f, args...) where S<:BroadcastStyle @ Base.Broadcast broadcast.jl:1319 with MethodInstance for Base.Broadcast.broadcasted(::Base.Broadcast.BroadcastStyle, ::typeof(esc), ::Any) (21 children)
   1 mt_cache
false
```

So it seems it worked. I'll check the implications in `TaylorIntegration` before proceeding...

cc: @lrnv, @PerezHz

**Comment by lbenet** [comment]
@PerezHz, it seems that no problems occur in TaylorIntegration, as far as I checked the tests, but it would be nice if you can double check this. Can you do it?

**Comment by lbenet** [comment]
I checked the invalidations wrt `IntervalArithmetic`, and they are none due to TS. Yet, when loading `IntervalArithmetic`, we get some  ambiguities that are detected by Aqua:
```julia
Aqua.detect_ambiguities(TaylorSeries; recursive = true)
2-element Vector{Tuple{Method, Method}}:
 (^(a::TaylorN{Interval{T}}, r::S) where {T<:Real, S<:Real} @ TaylorSeriesIAExt ~/.julia/dev/TaylorSeries/ext/TaylorSeriesIAExt.jl:46, ^(a::TaylorN, x::S) where S<:Rational @ TaylorSeries ~/.julia/dev/TaylorSeries/src/power.jl:50)
 (^(a::Taylor1{Interval{T}}, r::S) where {T<:Real, S<:Real} @ TaylorSeriesIAExt ~/.julia/dev/TaylorSeries/ext/TaylorSeriesIAExt.jl:22, ^(a::Taylor1, x::S) where S<:Rational @ TaylorSeries ~/.julia/dev/TaylorSeries/src/power.jl:50)
```

**Comment by lrnv** [comment]
@lbenet Looking at your coed I do not understand why, but indeed it solved the invalidations I was having. GG ! number of invals reduced from 502 to 192, which is great. The remaining ones are NOT from TaylorSeries.jl, so you are out of the woods: I'll wait for this PR to get merged and versionned and then I'll take these invalidations somewhere else :)

If you need something else from me do not hesitate to ping me again. Thanks a lot !

**Comment by PerezHz** [comment]
> @PerezHz, it seems that no problems occur in TaylorIntegration, as far as I checked the tests, but it would be nice if you can double check this. Can you do it?

Just double-checked and everything seems to be fine! 👍

**Comment by lbenet** [comment]
> Just double-checked and everything seems to be fine! 👍

Excellent! I guess this holds for PlanetaryEphemeris and NEOs...

**Comment by PerezHz** [comment]
> Excellent! I guess this holds for PlanetaryEphemeris and NEOs...

Indeed!

**Comment by PerezHz** [comment]
@lbenet: just to be clear on my previous comment, PlanetaryEphemeris and NEOs tests pass using this branch of TaylorSeries (a very small issue appeared on the latter, but that's completely unrelated to this PR).

**Comment by lbenet** [comment]
Merging!

**Pull request merged**
