### PR TITLE
Bump compat for IntervalArithmetic

### PR DESCRIPTION
**Pull request by mohamed82008**
This PR bumps the compat version of IntervalArithmetic.

### CODE REVIEW

**Comment by mohamed82008** [comment]
Some more fixes are needed to support IA 0.22.

**Comment by lbenet** [comment]
Thanks for opening this PR @mohamed82008 . 

`IntervalArithmetic` is undergoing very breaking changes, actually since v0.21, which is part of the reason we haven't those versions yet. The aim in IntervalArithmetic is to release a v1.0, eventually (hopefully soon). 

In any case, if you need IntervalArithmetic with v0.22, there is #345, which provides some (most?) of the fixes needed.

**Comment by lbenet** [comment]
If you agree, we can close this PR, and continue any discussion in #345 ...

**Comment by mohamed82008** [comment]
Sounds good.

**Pull request closed without merging**
